# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction

# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/ionosphere_data.csv)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
data_set=pd.read_csv('ionosphere_data.csv')

In [3]:
data_set.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [4]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [5]:
data_set.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [6]:
data_set=data_set.sample(frac=1)

In [7]:
data_set.drop('feature2',
  axis='columns', inplace=True)

In [8]:
data_set.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
314,1,0.79378,0.29492,0.64064,0.52312,0.41319,0.68158,0.14177,0.83548,-0.16831,...,-0.52540,0.01523,-0.48707,0.19030,-0.38059,0.31008,-0.23199,0.34572,-0.08036,g
340,1,0.19466,0.05725,0.04198,0.25191,-0.10557,0.48866,-0.18321,-0.18321,-0.41985,...,0.24692,0.03913,0.31092,-0.03817,0.26336,-0.16794,0.16794,-0.30153,-0.33588,g
244,1,0.00000,0.00000,1.00000,0.12889,0.88444,-0.02000,0.00000,0.00000,1.00000,...,0.00000,1.00000,-1.00000,0.00000,0.00000,1.00000,0.11778,0.90667,-0.09556,b
132,1,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,...,0.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,b
336,1,0.88420,0.36724,0.67123,0.67382,0.39613,0.86399,0.02424,0.93182,-0.35148,...,-0.69774,0.26028,-0.60678,0.44569,-0.43383,0.54209,-0.21542,0.56286,0.02823,g

In [9]:
data_set['label']=data_set['label'].map({'g':1,"b":0})

In [10]:
data_set.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
314,1,0.79378,0.29492,0.64064,0.52312,0.41319,0.68158,0.14177,0.83548,-0.16831,...,-0.52540,0.01523,-0.48707,0.19030,-0.38059,0.31008,-0.23199,0.34572,-0.08036,1
340,1,0.19466,0.05725,0.04198,0.25191,-0.10557,0.48866,-0.18321,-0.18321,-0.41985,...,0.24692,0.03913,0.31092,-0.03817,0.26336,-0.16794,0.16794,-0.30153,-0.33588,1
244,1,0.00000,0.00000,1.00000,0.12889,0.88444,-0.02000,0.00000,0.00000,1.00000,...,0.00000,1.00000,-1.00000,0.00000,0.00000,1.00000,0.11778,0.90667,-0.09556,0
132,1,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,...,0.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,0
336,1,0.88420,0.36724,0.67123,0.67382,0.39613,0.86399,0.02424,0.93182,-0.35148,...,-0.69774,0.26028,-0.60678,0.44569,-0.43383,0.54209,-0.21542,0.56286,0.02823,1

In [11]:
data=data_set.iloc[:,:33]
labels=data_set.iloc[:,33:]

In [12]:
data.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
314,1,0.79378,0.29492,0.64064,0.52312,0.41319,0.68158,0.14177,0.83548,-0.16831,...,-0.17437,-0.52540,0.01523,-0.48707,0.19030,-0.38059,0.31008,-0.23199,0.34572,-0.08036
340,1,0.19466,0.05725,0.04198,0.25191,-0.10557,0.48866,-0.18321,-0.18321,-0.41985,...,0.21645,0.24692,0.03913,0.31092,-0.03817,0.26336,-0.16794,0.16794,-0.30153,-0.33588
244,1,0.00000,0.00000,1.00000,0.12889,0.88444,-0.02000,0.00000,0.00000,1.00000,...,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,1.00000,0.11778,0.90667,-0.09556
132,1,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,...,0.00000,0.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000
336,1,0.88420,0.36724,0.67123,0.67382,0.39613,0.86399,0.02424,0.93182,-0.35148,...,0.00806,-0.69774,0.26028,-0.60678,0.44569,-0.43383,0.54209,-0.21542,0.56286,0.02823

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,labels, test_size=0.40, random_state=40)

In [14]:
x_train.shape

(210, 33)

In [15]:
x_test.shape

(141, 33)

In [16]:
y_train.shape

(210, 1)

In [17]:
y_test.shape

(141, 1)

In [18]:
mean=x_train.mean()
std=x_train.std()
x_train -= mean
x_train /=std
x_test -= mean
x_test /=std

In [19]:
x_test.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
103,0.314647,0.685538,-0.423744,0.039709,-0.519340,0.880590,-0.668497,0.950498,-0.192507,0.833140,...,1.085970,-0.255834,0.708576,-0.512195,0.797634,-0.438824,1.006305,-0.699290,0.709288,-0.994175
283,0.314647,0.558920,0.721007,0.120533,1.195389,-0.219890,1.649447,-1.097017,1.372098,-1.256209,...,-0.983691,-0.971536,-0.920380,-0.907522,-0.243998,-0.857111,0.021879,-0.661376,0.188385,0.239492
146,0.314647,-2.794969,0.247815,-1.109096,-0.228910,-1.140639,-0.164291,0.248271,-0.240498,-0.499582,...,-0.689971,-0.831151,-1.000855,0.100698,-1.998614,0.129896,-0.722613,-0.028273,-0.645907,0.151312
230,-3.163030,-1.379178,-0.130724,-1.234911,-0.228910,-1.140639,-0.292957,-1.022921,-0.376220,-0.840708,...,-0.747259,0.144465,0.932202,2.042382,-0.687614,0.063712,-0.664026,-0.028273,-0.645907,-0.059470
333,0.314647,0.724565,-0.113523,0.749530,-0.184189,0.956833,-0.252730,0.996546,-0.341497,0.901074,...,1.056656,0.218393,0.883115,0.226461,1.042433,0.236766,1.194101,0.102679,1.282368,0.164172

In [20]:
x_train.head(3)

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
185,0.314647,0.436855,0.922159,-0.228388,1.514131,-0.932653,1.631063,-1.791007,1.538787,-2.157238,...,0.625737,-0.457097,0.491954,0.254732,0.482209,0.970747,-0.074690,1.287074,-0.654132,1.501084
297,0.314647,0.630373,0.578676,0.373855,1.047153,0.116838,1.180958,-0.489976,1.635747,-0.756364,...,-2.272359,-0.831796,-2.363522,-1.249860,-1.439522,-1.751861,-0.918808,-2.007243,-0.450865,-2.191419
343,0.314647,-0.616624,-0.464275,0.161881,-0.284364,0.289732,-0.366533,0.110311,-0.509098,0.284299,...,0.077840,0.132726,-0.282087,-0.074791,-0.038488,-0.154559,-0.059749,-0.210197,-0.081793,-0.246083

In [21]:
x_test.head(3)

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
103,0.314647,0.685538,-0.423744,0.039709,-0.519340,0.880590,-0.668497,0.950498,-0.192507,0.833140,...,1.085970,-0.255834,0.708576,-0.512195,0.797634,-0.438824,1.006305,-0.699290,0.709288,-0.994175
283,0.314647,0.558920,0.721007,0.120533,1.195389,-0.219890,1.649447,-1.097017,1.372098,-1.256209,...,-0.983691,-0.971536,-0.920380,-0.907522,-0.243998,-0.857111,0.021879,-0.661376,0.188385,0.239492
146,0.314647,-2.794969,0.247815,-1.109096,-0.228910,-1.140639,-0.164291,0.248271,-0.240498,-0.499582,...,-0.689971,-0.831151,-1.000855,0.100698,-1.998614,0.129896,-0.722613,-0.028273,-0.645907,0.151312

In [22]:
train=x_train

In [23]:
test=x_test

In [24]:
train.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
185,0.314647,0.436855,0.922159,-0.228388,1.514131,-0.932653,1.631063,-1.791007,1.538787,-2.157238,...,0.625737,-0.457097,0.491954,0.254732,0.482209,0.970747,-0.074690,1.287074,-0.654132,1.501084
297,0.314647,0.630373,0.578676,0.373855,1.047153,0.116838,1.180958,-0.489976,1.635747,-0.756364,...,-2.272359,-0.831796,-2.363522,-1.249860,-1.439522,-1.751861,-0.918808,-2.007243,-0.450865,-2.191419
343,0.314647,-0.616624,-0.464275,0.161881,-0.284364,0.289732,-0.366533,0.110311,-0.509098,0.284299,...,0.077840,0.132726,-0.282087,-0.074791,-0.038488,-0.154559,-0.059749,-0.210197,-0.081793,-0.246083
329,0.314647,0.521705,-0.130724,0.673799,-0.291710,0.822553,-0.318072,0.812559,-0.336503,0.801138,...,1.080378,0.245992,0.725996,0.143920,0.969564,0.083091,1.210749,0.087323,1.255607,-0.086900
48,0.314647,0.738653,-0.109550,0.739947,-0.316290,0.905760,-0.410279,0.928553,-0.527599,0.960512,...,0.874910,-0.265325,0.569296,-0.309696,0.745066,-0.441705,0.777882,-0.514732,0.802687,-0.596870

In [25]:
train_label=np.asarray(y_train)
test_label=np.asarray(y_test)

In [26]:
# now we have the following
#train
#test
#train_label
#test_label

In [27]:
train.shape

(210, 33)

In [28]:
from tensorflow.keras import models
from tensorflow.keras import layers

mymodel=models.Sequential()
mymodel.add(layers.Dense(16, activation='relu', input_shape=(train.shape[1],)))
mymodel.add(layers.Dense(12, activation='relu'))
mymodel.add(layers.Dense(1, activation='sigmoid'))

In [29]:
mymodel.compile(optimizer='rmsprop',
               loss='binary_crossentropy',
               metrics=['accuracy'])

In [30]:
mymodel.fit(train,train_label, epochs=100,batch_size=1)

Epoch 1/100
210/210 [==============================] - 0s 668us/step - loss: 0.6043 - accuracy: 0.7238
Epoch 2/100
210/210 [==============================] - 0s 585us/step - loss: 0.4479 - accuracy: 0.8286
Epoch 3/100
210/210 [==============================] - 0s 611us/step - loss: 0.3677 - accuracy: 0.8571
Epoch 4/100
210/210 [==============================] - 0s 602us/step - loss: 0.3161 - accuracy: 0.8762
Epoch 5/100
210/210 [==============================] - 0s 607us/step - loss: 0.2789 - accuracy: 0.8857
Epoch 6/100
210/210 [==============================] - 0s 599us/step - loss: 0.2617 - accuracy: 0.8905
Epoch 7/100
210/210 [==============================] - 0s 606us/step - loss: 0.2471 - accuracy: 0.9000
Epoch 8/100
210/210 [==============================] - 0s 610us/step - loss: 0.2099 - accuracy: 0.9095
Epoch 9/100
210/210 [==============================] - 0s 645us/step - loss: 0.1969 - accuracy: 0.9190
Epoch 10/100
210/210 [==============================] - 0s 601us/step - loss: 0.1846 - accuracy: 0.9333
Epoch 11/100
210/210 [==============================] - 0s 608us/step - loss: 0.1633 - accuracy: 0.9429
Epoch 12/100
210/210 [==============================] - 0s 601us/step - loss: 0.1716 - accuracy: 0.9429
Epoch 13/100
210/210 [==============================] - 0s 602us/step - loss: 0.1601 - accuracy: 0.9476
Epoch 14/100
210/210 [==============================] - 0s 610us/step - loss: 0.1457 - accuracy: 0.9524
Epoch 15/100
210/210 [==============================] - 0s 605us/step - loss: 0.1361 - accuracy: 0.9524
Epoch 16/100
210/210 [==============================] - 0s 619us/step - loss: 0.1338 - accuracy: 0.9524
Epoch 17/100
210/210 [==============================] - 0s 628us/step - loss: 0.1343 - accuracy: 0.9524
Epoch 18/100
210/210 [==============================] - 0s 605us/step - loss: 0.1255 - accuracy: 0.9571
Epoch 19/100
210/210 [==============================] - 0s 617us/step - loss: 0.1134 - accuracy: 0.9667
Epoch 20/100
210/210 [==============================] - 0s 598us/step - loss: 0.1284 - accuracy: 0.9619
Epoch 21/100
210/210 [==============================] - 0s 605us/step - loss: 0.1042 - accuracy: 0.9619
Epoch 22/100
210/210 [==============================] - 0s 604us/step - loss: 0.1166 - accuracy: 0.9619
Epoch 23/100
210/210 [==============================] - 0s 600us/step - loss: 0.1010 - accuracy: 0.9667
Epoch 24/100
210/210 [==============================] - 0s 617us/step - loss: 0.0904 - accuracy: 0.9619
Epoch 25/100
210/210 [==============================] - 0s 606us/step - loss: 0.1085 - accuracy: 0.9667
Epoch 26/100
210/210 [==============================] - 0s 599us/step - loss: 0.0997 - accuracy: 0.9714
Epoch 27/100
210/210 [==============================] - 0s 599us/step - loss: 0.0948 - accuracy: 0.9667
Epoch 28/100
210/210 [==============================] - 0s 607us/step - loss: 0.0864 - accuracy: 0.9714
Epoch 29/100
210/210 [==============================] - 0s 600us/step - loss: 0.0840 - accuracy: 0.9714
Epoch 30/100
210/210 [==============================] - 0s 612us/step - loss: 0.0802 - accuracy: 0.9667
Epoch 31/100
210/210 [==============================] - 0s 602us/step - loss: 0.0836 - accuracy: 0.9714
Epoch 32/100
210/210 [==============================] - 0s 608us/step - loss: 0.0805 - accuracy: 0.9667
Epoch 33/100
210/210 [==============================] - 0s 612us/step - loss: 0.0704 - accuracy: 0.9714
Epoch 34/100
210/210 [==============================] - 0s 603us/step - loss: 0.0668 - accuracy: 0.9714
Epoch 35/100
210/210 [==============================] - 0s 600us/step - loss: 0.0706 - accuracy: 0.9714
Epoch 36/100
210/210 [==============================] - 0s 600us/step - loss: 0.0683 - accuracy: 0.9714
Epoch 37/100
210/210 [==============================] - 0s 606us/step - loss: 0.0669 - accuracy: 0.9762
Epoch 38/100
210/210 [==============================] - 0s 604us/step - loss: 0.0540 - accuracy: 0.9762
Epoch 39/100
210/210 [==============================] - 0s 622us/step - loss: 0.0647 - accuracy: 0.9714
Epoch 40/100
210/210 [==============================] - 0s 668us/step - loss: 0.0664 - accuracy: 0.9714
Epoch 41/100
210/210 [==============================] - 0s 622us/step - loss: 0.0458 - accuracy: 0.9762
Epoch 42/100
210/210 [==============================] - 0s 603us/step - loss: 0.0581 - accuracy: 0.9714
Epoch 43/100
210/210 [==============================] - 0s 612us/step - loss: 0.0501 - accuracy: 0.9810
Epoch 44/100
210/210 [==============================] - 0s 618us/step - loss: 0.0588 - accuracy: 0.9714
Epoch 45/100
210/210 [==============================] - 0s 812us/step - loss: 0.0589 - accuracy: 0.9714
Epoch 46/100
210/210 [==============================] - 0s 775us/step - loss: 0.0624 - accuracy: 0.9810
Epoch 47/100
210/210 [==============================] - 0s 764us/step - loss: 0.0364 - accuracy: 0.9810
Epoch 48/100
210/210 [==============================] - 0s 602us/step - loss: 0.0463 - accuracy: 0.9810
Epoch 49/100
210/210 [==============================] - 0s 653us/step - loss: 0.0337 - accuracy: 0.9857
Epoch 50/100
210/210 [==============================] - 0s 771us/step - loss: 0.0389 - accuracy: 0.9905
Epoch 51/100
210/210 [==============================] - 0s 803us/step - loss: 0.0374 - accuracy: 0.9810
Epoch 52/100
210/210 [==============================] - 0s 848us/step - loss: 0.0403 - accuracy: 0.9857
Epoch 53/100
210/210 [==============================] - 0s 655us/step - loss: 0.0310 - accuracy: 0.9857
Epoch 54/100
210/210 [==============================] - 0s 649us/step - loss: 0.0355 - accuracy: 0.9905
Epoch 55/100
210/210 [==============================] - 0s 573us/step - loss: 0.0517 - accuracy: 0.9810
Epoch 56/100
210/210 [==============================] - 0s 573us/step - loss: 0.0320 - accuracy: 0.9857
Epoch 57/100
210/210 [==============================] - 0s 563us/step - loss: 0.0262 - accuracy: 0.9905
Epoch 58/100
210/210 [==============================] - 0s 559us/step - loss: 0.0280 - accuracy: 0.9857
Epoch 59/100
210/210 [==============================] - 0s 569us/step - loss: 0.0397 - accuracy: 0.9857
Epoch 60/100
210/210 [==============================] - 0s 581us/step - loss: 0.0230 - accuracy: 0.9905
Epoch 61/100
210/210 [==============================] - 0s 585us/step - loss: 0.0278 - accuracy: 0.9905
Epoch 62/100
210/210 [==============================] - 0s 594us/step - loss: 0.0213 - accuracy: 0.9905
Epoch 63/100
210/210 [==============================] - 0s 573us/step - loss: 0.0236 - accuracy: 0.9905
Epoch 64/100
210/210 [==============================] - 0s 588us/step - loss: 0.0204 - accuracy: 0.9905
Epoch 65/100
210/210 [==============================] - 0s 571us/step - loss: 0.0150 - accuracy: 0.9905
Epoch 66/100
210/210 [==============================] - 0s 569us/step - loss: 0.0211 - accuracy: 0.9905
Epoch 67/100
210/210 [==============================] - 0s 579us/step - loss: 0.0175 - accuracy: 0.9905
Epoch 68/100
210/210 [==============================] - 0s 567us/step - loss: 0.0141 - accuracy: 0.9905
Epoch 69/100
210/210 [==============================] - 0s 588us/step - loss: 0.0278 - accuracy: 0.9857
Epoch 70/100
210/210 [==============================] - 0s 754us/step - loss: 0.0146 - accuracy: 0.9952
Epoch 71/100
210/210 [==============================] - 0s 675us/step - loss: 0.0135 - accuracy: 1.0000
Epoch 72/100
210/210 [==============================] - 0s 597us/step - loss: 0.0171 - accuracy: 0.9857
Epoch 73/100
210/210 [==============================] - 0s 557us/step - loss: 0.0163 - accuracy: 0.9905
Epoch 74/100
210/210 [==============================] - 0s 595us/step - loss: 0.0188 - accuracy: 0.9905
Epoch 75/100
210/210 [==============================] - 0s 582us/step - loss: 0.0167 - accuracy: 0.9905
Epoch 76/100
210/210 [==============================] - 0s 651us/step - loss: 0.0157 - accuracy: 0.9952
Epoch 77/100
210/210 [==============================] - 0s 617us/step - loss: 0.0124 - accuracy: 0.9952
Epoch 78/100
210/210 [==============================] - 0s 669us/step - loss: 0.0130 - accuracy: 0.9952
Epoch 79/100
210/210 [==============================] - 0s 667us/step - loss: 0.0243 - accuracy: 0.9905
Epoch 80/100
210/210 [==============================] - 0s 625us/step - loss: 0.0102 - accuracy: 0.9952
Epoch 81/100
210/210 [==============================] - 0s 608us/step - loss: 0.0093 - accuracy: 0.9952
Epoch 82/100
210/210 [==============================] - 0s 586us/step - loss: 0.0103 - accuracy: 0.9952
Epoch 83/100
210/210 [==============================] - 0s 591us/step - loss: 0.0092 - accuracy: 1.0000
Epoch 84/100
210/210 [==============================] - 0s 578us/step - loss: 0.0114 - accuracy: 0.9952
Epoch 85/100
210/210 [==============================] - 0s 676us/step - loss: 0.0085 - accuracy: 0.9952
Epoch 86/100
210/210 [==============================] - 0s 809us/step - loss: 0.0084 - accuracy: 0.9952
Epoch 87/100
210/210 [==============================] - 0s 740us/step - loss: 0.0079 - accuracy: 0.9952
Epoch 88/100
210/210 [==============================] - 0s 611us/step - loss: 0.0085 - accuracy: 0.9952
Epoch 89/100
210/210 [==============================] - 0s 601us/step - loss: 0.0054 - accuracy: 1.0000
Epoch 90/100
210/210 [==============================] - 0s 587us/step - loss: 0.0056 - accuracy: 0.9952
Epoch 91/100
210/210 [==============================] - 0s 781us/step - loss: 0.0090 - accuracy: 0.9952
Epoch 92/100
210/210 [==============================] - 0s 681us/step - loss: 0.0041 - accuracy: 1.0000
Epoch 93/100
210/210 [==============================] - 0s 562us/step - loss: 0.0061 - accuracy: 0.9952
Epoch 94/100
210/210 [==============================] - 0s 597us/step - loss: 0.0053 - accuracy: 1.0000
Epoch 95/100
210/210 [==============================] - 0s 574us/step - loss: 0.0026 - accuracy: 1.0000
Epoch 96/100
210/210 [==============================] - 0s 578us/step - loss: 0.0049 - accuracy: 0.9952
Epoch 97/100
210/210 [==============================] - 0s 599us/step - loss: 0.0044 - accuracy: 1.0000
Epoch 98/100
210/210 [==============================] - 0s 630us/step - loss: 0.0046 - accuracy: 1.0000
Epoch 99/100
210/210 [==============================] - 0s 589us/step - loss: 0.0049 - accuracy: 0.9952
Epoch 100/100
210/210 [==============================] - 0s 579us/step - loss: 0.0055 - accuracy: 0.9952

In [31]:
results = mymodel.evaluate(test, test_label)

5/5 [==============================] - 0s 798us/step - loss: 2.1667 - accuracy: 0.8298

In [32]:
pred=mymodel.predict(test)
pred[0:10]

array([[1.0000000e+00],
       [1.0000000e+00],
       [1.1881872e-10],
       [9.9866043e-19],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.0404482e-17],
       [9.9996984e-01],
       [1.8174215e-32],
       [1.1447370e-03]], dtype=float32)

In [33]:
train_label[0:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]], dtype=int64)

In [34]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import regularizers

mymodel=models.Sequential()
mymodel.add(layers.Dense(16,kernel_regularizer=regularizers.l2(0.001),
                         activation='relu', input_shape=(train.shape[1],)))
mymodel.add(layers.Dense(12,kernel_regularizer=regularizers.l2(0.001),
                         activation='relu'))
mymodel.add(layers.Dense(1, activation='sigmoid'))

In [35]:
mymodel.compile(optimizer='rmsprop',
               loss='binary_crossentropy',
               metrics=['accuracy'])

In [36]:
mymodel.fit(train,train_label, epochs=100,batch_size=1, verbose=0)

In [37]:
results = mymodel.evaluate(test, test_label)
results

5/5 [==============================] - 0s 600us/step - loss: 0.8841 - accuracy: 0.8156

[0.8840561509132385, 0.8156028389930725]

In [38]:
pred=mymodel.predict(test)
pred[0:10]

array([[9.9973577e-01],
       [9.9827325e-01],
       [1.2353063e-03],
       [3.4348582e-07],
       [9.9982125e-01],
       [9.9959195e-01],
       [2.8372506e-07],
       [9.4606054e-01],
       [3.5285143e-07],
       [2.1421909e-04]], dtype=float32)

In [39]:
train_label[0:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]], dtype=int64)